/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface RfTimerLogin {
    }
}
declare global {
    interface HTMLRfTimerLoginElement extends Components.RfTimerLogin, HTMLStencilElement {
    }
    var HTMLRfTimerLoginElement: {
        prototype: HTMLRfTimerLoginElement;
        new (): HTMLRfTimerLoginElement;
    };
    interface HTMLElementTagNameMap {
        "rf-timer-login": HTMLRfTimerLoginElement;
    }
}
declare namespace LocalJSX {
    interface RfTimerLogin {
    }
    interface IntrinsicElements {
        "rf-timer-login": RfTimerLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-timer-login": LocalJSX.RfTimerLogin & JSXBase.HTMLAttributes<HTMLRfTimerLoginElement>;
        }
    }
}
